<?php
/**
 * ambulance export
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Analyse once via WP-CLI; write manifests + bash cleaners that run without WordPress.
 */
class DP_Ambulance_Command_Export extends DP_Ambulance_Command_Purge_Files {

	/**
	 * Export purge targets and DB hits to .txt manifests + offline bash cleaners.
	 *
	 * Does not delete anything. Run the generated ./clean-all.sh later (no WP bootstrap).
	 *
	 * ## OPTIONS
	 *
	 * [--dir=<path>]
	 * : Output directory. Default: {ABSPATH}/../ambulance-analysis/{domain}/{Ymd-His}/
	 *
	 * @when after_wp_load
	 *
	 * @param array $args       Positional args.
	 * @param array $assoc_args Assoc args.
	 */
	public function __invoke( $args, $assoc_args ) {
		unset( $args );
		global $wpdb;

		$dir = isset( $assoc_args['dir'] ) ? (string) $assoc_args['dir'] : '';
		if ( '' === $dir ) {
			$dir = dirname( untrailingslashit( ABSPATH ) ) . '/ambulance-analysis/' . $this->site_domain_slug() . '/' . gmdate( 'Ymd-His' );
		}
		$dir = rtrim( $dir, '/\\' );

		if ( ! wp_mkdir_p( $dir ) ) {
			WP_CLI::error( 'Could not create output dir: ' . $dir );
		}

		WP_CLI::log( '== Ambulance export ==' );
		WP_CLI::log( 'Output: ' . $dir );

		$files = $this->collect_file_targets();
		$dirs  = $this->collect_dir_targets();

		$host = $this->probe_host_artifacts();
		foreach ( $host['files'] as $path ) {
			if ( ! in_array( $path, $files, true ) ) {
				$files[] = $path;
			}
		}
		foreach ( $host['dirs'] as $path ) {
			if ( ! in_array( $path, $dirs, true ) ) {
				$dirs[] = $path;
			}
		}
		sort( $files );
		sort( $dirs );

		$options = $this->collect_option_names();
		$users   = $this->collect_regex_flagged_admins();
		$cron    = $this->build_cron_manifest_lines( $host['cron_files'], $host['crontab_needles'] );

		$watch = $this->collect_watch_paths( $files );

		$this->write_lines( $dir . '/files.txt', $files );
		$this->write_lines( $dir . '/dirs.txt', $dirs );
		$this->write_lines( $dir . '/options.txt', $options );
		$this->write_lines( $dir . '/users.txt', $users );
		$this->write_lines( $dir . '/cron.txt', $cron );
		$this->write_lines( $dir . '/watch-paths.txt', $watch );
		$this->write_db_env( $dir . '/db.env' );
		$this->write_site_env( $dir . '/site.env' );
		$this->write_readme( $dir, count( $files ), count( $dirs ), count( $options ), count( $users ), count( $cron ), count( $watch ) );
		$this->write_bash_scripts( $dir );

		WP_CLI::success(
			sprintf(
				'Exported %d file(s), %d dir(s), %d option(s), %d user(s), %d cron line(s), %d watch path(s).',
				count( $files ),
				count( $dirs ),
				count( $options ),
				count( $users ),
				count( $cron ),
				count( $watch )
			)
		);
		WP_CLI::log( 'Next (no WordPress): cd ' . $dir . ' && DRY_RUN=1 ./clean-all.sh && ./clean-all.sh' );
		WP_CLI::log( 'Live containment: INTERVAL=5 ./guard.sh   (Ctrl+C to stop; found=0 ≠ clean)' );
		unset( $wpdb );
	}

	/**
	 * High-value paths for guard mode (fixed drop-ins + current purge hits).
	 *
	 * @param string[] $files Purge file targets.
	 * @return string[]
	 */
	protected function collect_watch_paths( $files ) {
		$fixed = array(
			WP_CONTENT_DIR . '/object-cache.php',
			WP_CONTENT_DIR . '/advanced-cache.php',
			WP_CONTENT_DIR . '/db.php',
			WP_CONTENT_DIR . '/.user.ini',
			WP_CONTENT_DIR . '/user.ini',
			WP_CONTENT_DIR . '/admin-helper.php',
			WP_CONTENT_DIR . '/mu-plugins/boot-loader.php',
			ABSPATH . '.user.ini',
			ABSPATH . 'wp-config.php',
		);
		$out = array();
		foreach ( array_merge( $fixed, $files ) as $path ) {
			$out[ $path ] = true;
		}
		$paths = array_keys( $out );
		sort( $paths );
		return $paths;
	}

	/**
	 * @param string $path Path to site.env.
	 */
	protected function write_site_env( $path ) {
		$content = WP_CONTENT_DIR;
		$abs     = untrailingslashit( ABSPATH );
		$qbase   = dirname( $abs ) . '/ambulance-quarantine';
		$lines   = array(
			'# Generated by wp am export — paths for guard.sh / quarantine bash.',
			'ABSPATH=' . $this->shell_quote_env( $abs ),
			'WP_CONTENT_DIR=' . $this->shell_quote_env( $content ),
			'QUARANTINE_BASE=' . $this->shell_quote_env( $qbase ),
		);
		if ( false === file_put_contents( $path, implode( "\n", $lines ) . "\n" ) ) {
			WP_CLI::error( 'Failed to write: ' . $path );
		}
		@chmod( $path, 0600 );
		WP_CLI::log( 'Wrote ' . $path . ' (mode 600)' );
	}

	/**
	 * Known implant option names still present in the DB (tab-separated for bash).
	 *
	 * @return string[] Lines: table\tcolumn\toption_name
	 */
	protected function collect_option_names() {
		global $wpdb;

		$names = DP_Ambulance_Command_Options::resolve_purgeable_option_names();
		$out   = array();
		$table = $wpdb->options;
		foreach ( $names as $name ) {
			$exists = $wpdb->get_var(
				$wpdb->prepare(
					"SELECT option_id FROM {$wpdb->options} WHERE option_name = %s LIMIT 1",
					$name
				)
			);
			if ( $exists ) {
				$out[] = $table . "\toption_name\t" . $name;
			}
		}
		sort( $out );
		return $out;
	}

	/**
	 * Admins matching strong login regexes only.
	 *
	 * @return string[] Lines: ID\tlogin
	 */
	protected function collect_regex_flagged_admins() {
		$users = get_users(
			array(
				'role'   => 'administrator',
				'fields' => array( 'ID', 'user_login' ),
			)
		);
		$out = array();
		foreach ( $users as $user ) {
			foreach ( DP_Ambulance_Command_Users::$user_login_regexes as $regex ) {
				if ( preg_match( $regex, $user->user_login ) ) {
					$out[] = (int) $user->ID . "\t" . $user->user_login;
					break;
				}
			}
		}
		return $out;
	}

	/**
	 * @param string[] $cron_files       Absolute /etc/cron.d paths.
	 * @param string[] $crontab_needles  Substrings to strip from user crontab.
	 * @return string[]
	 */
	protected function build_cron_manifest_lines( $cron_files, $crontab_needles ) {
		$lines   = array();
		$lines[] = 'WP_CRON_CLEAR';
		foreach ( $cron_files as $path ) {
			$lines[] = 'HOST_FILE' . "\t" . $path;
		}
		foreach ( $crontab_needles as $needle ) {
			$lines[] = 'CRONTAB_NEEDLE' . "\t" . $needle;
		}
		return $lines;
	}

	/**
	 * Probe host paths outside wp-content (home + /tmp + /etc/cron.d).
	 *
	 * @return array{files:string[],dirs:string[],cron_files:string[],crontab_needles:string[]}
	 */
	protected function probe_host_artifacts() {
		$files           = array();
		$dirs            = array();
		$cron_files      = array();
		$crontab_needles = array( 'cron-helper', 'db-helper', 'maintenance-helper' );

		$homes = array_unique(
			array_filter(
				array(
					isset( $_SERVER['HOME'] ) ? (string) $_SERVER['HOME'] : '',
					getenv( 'HOME' ) ? (string) getenv( 'HOME' ) : '',
					dirname( dirname( untrailingslashit( ABSPATH ) ) ),
				)
			)
		);

		$helper_globs = array(
			'cron-helper*',
			'db-helper*',
			'maintenance-helper*',
		);

		foreach ( $homes as $home ) {
			$home = rtrim( $home, '/\\' );
			if ( '' === $home || ! is_dir( $home ) ) {
				continue;
			}
			foreach ( glob( $home . '/.wp-cache-*', GLOB_ONLYDIR ) ?: array() as $cache_dir ) {
				$dirs[] = $cache_dir;
				foreach ( $helper_globs as $pattern ) {
					foreach ( glob( $cache_dir . '/' . $pattern ) ?: array() as $hit ) {
						if ( is_file( $hit ) ) {
							$files[] = $hit;
						} elseif ( is_dir( $hit ) ) {
							$dirs[] = $hit;
						}
					}
				}
			}
			foreach ( $helper_globs as $pattern ) {
				foreach ( glob( $home . '/' . $pattern ) ?: array() as $hit ) {
					if ( is_file( $hit ) ) {
						$files[] = $hit;
					} elseif ( is_dir( $hit ) ) {
						$dirs[] = $hit;
					}
				}
			}
		}

		foreach ( $helper_globs as $pattern ) {
			foreach ( glob( '/tmp/' . $pattern ) ?: array() as $hit ) {
				if ( is_file( $hit ) ) {
					$files[] = $hit;
				} elseif ( is_dir( $hit ) ) {
					$dirs[] = $hit;
				}
			}
		}

		foreach ( glob( '/etc/cron.d/php-cache-*' ) ?: array() as $hit ) {
			if ( is_file( $hit ) ) {
				$cron_files[] = $hit;
			}
		}

		$files      = array_values( array_unique( $files ) );
		$dirs       = array_values( array_unique( $dirs ) );
		$cron_files = array_values( array_unique( $cron_files ) );

		return compact( 'files', 'dirs', 'cron_files', 'crontab_needles' );
	}

	/**
	 * @param string   $path  File path.
	 * @param string[] $lines Lines.
	 */
	protected function write_lines( $path, $lines ) {
		$body = $lines ? ( implode( "\n", $lines ) . "\n" ) : '';
		if ( false === file_put_contents( $path, $body ) ) {
			WP_CLI::error( 'Failed to write: ' . $path );
		}
		WP_CLI::log( 'Wrote ' . $path . ' (' . count( $lines ) . ' line(s))' );
	}

	/**
	 * @param string $path Path to db.env.
	 */
	protected function write_db_env( $path ) {
		global $wpdb;

		$host = defined( 'DB_HOST' ) ? DB_HOST : 'localhost';
		$user = defined( 'DB_USER' ) ? DB_USER : '';
		$pass = defined( 'DB_PASSWORD' ) ? DB_PASSWORD : '';
		$name = defined( 'DB_NAME' ) ? DB_NAME : '';
		$pref = $wpdb->prefix;

		$lines = array(
			'# Generated by wp am export — chmod 600. Do not commit.',
			'DB_HOST=' . $this->shell_quote_env( $host ),
			'DB_USER=' . $this->shell_quote_env( $user ),
			'DB_PASSWORD=' . $this->shell_quote_env( $pass ),
			'DB_NAME=' . $this->shell_quote_env( $name ),
			'TABLE_PREFIX=' . $this->shell_quote_env( $pref ),
		);
		if ( false === file_put_contents( $path, implode( "\n", $lines ) . "\n" ) ) {
			WP_CLI::error( 'Failed to write: ' . $path );
		}
		@chmod( $path, 0600 );
		WP_CLI::log( 'Wrote ' . $path . ' (mode 600)' );
	}

	/**
	 * Escape a value for KEY='value' in a sourced env file.
	 *
	 * @param string $value Raw value.
	 * @return string Quoted for single-quote shell assignment.
	 */
	protected function shell_quote_env( $value ) {
		return "'" . str_replace( "'", "'\\''", (string) $value ) . "'";
	}

	/**
	 * @param string $dir     Output dir.
	 * @param int    $n_files File count.
	 * @param int    $n_dirs  Dir count.
	 * @param int    $n_opts  Option count.
	 * @param int    $n_users User count.
	 * @param int    $n_cron  Cron line count.
	 * @param int    $n_watch Watch path count.
	 */
	protected function write_readme( $dir, $n_files, $n_dirs, $n_opts, $n_users, $n_cron, $n_watch = 0 ) {
		$generated = $this->iso_now();
		$site      = $this->site_url();
		$abspath   = $this->abspath();
		$text      = <<<TXT
Ambulance offline cleanup pack
==============================
Generated: {$generated}
Site:      {$site}
ABSPATH:   {$abspath}

Counts: files={$n_files} dirs={$n_dirs} options={$n_opts} users={$n_users} cron_lines={$n_cron} watch={$n_watch}

Workflow (NO WordPress / NO wp-cli on cleanup):
  1) cd {$dir}
  2) DRY_RUN=1 ./clean-all.sh     # preview (delete)
  3) QUARANTINE=1 DRY_RUN=1 ./clean-all.sh   # preview (move to quarantine)
  4) QUARANTINE=1 ./clean-all.sh  # apply quarantine (preferred)
     or ./clean-all.sh            # apply delete

Order (engine-first-ish):
  clean-files.sh → clean-dirs.sh → clean-options.sh → clean-cron.sh → clean-users.sh

Live containment (while site stays online):
  INTERVAL=5 ./guard.sh
  - Re-checks watch-paths.txt + known drop-in markers every INTERVAL seconds
  - Quarantines returning files (first + newest copies under QUARANTINE_BASE)
  - found=0 does NOT mean the site is clean
  - Ctrl+C to stop; use only for a short monitored cleanup window

Notes:
  - db.env / site.env hold secrets/paths (chmod 600). Delete this directory when done.
  - users.txt only includes regex-flagged rogue admins (not loose prefixes).
  - cron.txt clears the entire WP cron option (same as wp am fix), plus host cron.d / crontab needles.
  - Heuristic-only PHP hits are NOT listed; review with: wp am files
  - After file cleanup, also run: wp am sanitize --dry-run && wp am sanitize --yes

TXT;
		$path = $dir . '/README.txt';
		if ( false === file_put_contents( $path, $text ) ) {
			WP_CLI::error( 'Failed to write: ' . $path );
		}
		WP_CLI::log( 'Wrote ' . $path );
	}

	/**
	 * @return string
	 */
	protected function iso_now() {
		return gmdate( 'c' );
	}

	/**
	 * @return string
	 */
	protected function site_url() {
		return home_url( '/' );
	}

	/**
	 * Filesystem-safe site host for ambulance-analysis/{domain}/…
	 *
	 * @return string
	 */
	protected function site_domain_slug() {
		$host = wp_parse_url( home_url( '/' ), PHP_URL_HOST );
		if ( ! is_string( $host ) || '' === $host ) {
			$host = wp_parse_url( site_url( '/' ), PHP_URL_HOST );
		}
		if ( ! is_string( $host ) || '' === $host ) {
			return 'unknown-site';
		}

		$host = strtolower( $host );
		$host = preg_replace( '/:\d+$/', '', $host );
		$host = preg_replace( '/[^a-z0-9._-]+/', '-', $host );
		$host = trim( (string) $host, '.-' );

		return '' !== $host ? $host : 'unknown-site';
	}

	/**
	 * @return string
	 */
	protected function abspath() {
		return ABSPATH;
	}

	/**
	 * Write clean-*.sh scripts into $dir.
	 *
	 * @param string $dir Output dir.
	 */
	protected function write_bash_scripts( $dir ) {
		$scripts = array(
			'clean-files.sh'   => $this->script_clean_files(),
			'clean-dirs.sh'    => $this->script_clean_dirs(),
			'clean-options.sh' => $this->script_clean_options(),
			'clean-cron.sh'    => $this->script_clean_cron(),
			'clean-users.sh'   => $this->script_clean_users(),
			'clean-all.sh'     => $this->script_clean_all(),
			'guard.sh'         => $this->script_guard(),
		);
		foreach ( $scripts as $name => $body ) {
			$path = $dir . '/' . $name;
			if ( false === file_put_contents( $path, $body ) ) {
				WP_CLI::error( 'Failed to write: ' . $path );
			}
			@chmod( $path, 0755 );
			WP_CLI::log( 'Wrote ' . $path );
		}
	}

	/**
	 * Shared bash preamble: cd to script dir, DRY_RUN, helpers.
	 *
	 * @return string
	 */
	protected function bash_preamble() {
		return <<<'BASH'
#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"
DRY_RUN="${DRY_RUN:-0}"
QUARANTINE="${QUARANTINE:-0}"

log() { printf '%s\n' "$*"; }
run() {
  if [[ "$DRY_RUN" == "1" ]]; then
    log "[dry-run] $*"
  else
    log "+ $*"
    eval "$@"
  fi
}

load_site_env() {
  if [[ -f "$DIR/site.env" ]]; then
    # shellcheck disable=SC1091
    source "$DIR/site.env"
  fi
  QUARANTINE_BASE="${QUARANTINE_BASE:-$(dirname "$DIR")/ambulance-quarantine}"
}

# Move path into quarantine: durable first/ copy + newest run copy. Removes source.
quarantine_move() {
  local src="$1"
  local rel="$2"
  load_site_env
  local run_id="${QUARANTINE_RUN:-$(date -u +%Y%m%d-%H%M%S)}"
  local first="$QUARANTINE_BASE/first/$rel"
  local dest="$QUARANTINE_BASE/$run_id/$rel"
  mkdir -p "$(dirname "$first")" "$(dirname "$dest")"
  chmod 700 "$(dirname "$first")" "$(dirname "$dest")" 2>/dev/null || true
  if [[ ! -e "$first" ]]; then
    if [[ -d "$src" ]]; then
      cp -a -- "$src" "$first"
    else
      cp -a -- "$src" "$first"
    fi
  fi
  rm -rf -- "$dest"
  mv -- "$src" "$dest"
  log "[MOVED] $src -> $dest (first=$first)"
}

rel_key_from_abspath() {
  local path="$1"
  load_site_env
  local content="${WP_CONTENT_DIR:-}"
  local abs="${ABSPATH:-}"
  if [[ -n "$content" && "$path" == "$content"/* ]]; then
    printf 'wp-content/%s\n' "${path#"$content"/}"
    return
  fi
  if [[ -n "$abs" && "$path" == "$abs"/* ]]; then
    printf '%s\n' "${path#"$abs"/}"
    return
  fi
  printf 'outside/%s\n' "$(basename "$path")"
}

BASH;
	}

	/**
	 * @return string
	 */
	protected function bash_load_db_env() {
		return <<<'BASH'
if [[ ! -f "$DIR/db.env" ]]; then
  echo "Missing db.env in $DIR" >&2
  exit 1
fi
# shellcheck disable=SC1091
source "$DIR/db.env"
mysql_cmd() {
  # -p must be adjacent to password (mysql client quirk).
  mysql -h"$DB_HOST" -u"$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" "$@"
}

BASH;
	}

	/**
	 * @return string
	 */
	protected function script_clean_files() {
		return $this->bash_preamble() . <<<'BASH'
MANIFEST="$DIR/files.txt"
if [[ ! -f "$MANIFEST" ]]; then
  echo "Missing files.txt" >&2
  exit 1
fi
load_site_env
export QUARANTINE_RUN="${QUARANTINE_RUN:-$(date -u +%Y%m%d-%H%M%S)}"
count=0
while IFS= read -r path || [[ -n "$path" ]]; do
  [[ -z "$path" || "$path" == \#* ]] && continue
  if [[ ! -e "$path" && ! -L "$path" ]]; then
    log "skip (missing): $path"
    continue
  fi
  if [[ "$QUARANTINE" == "1" ]]; then
    rel="$(rel_key_from_abspath "$path")"
    if [[ "$DRY_RUN" == "1" ]]; then
      log "[dry-run] quarantine $path -> $QUARANTINE_BASE/$QUARANTINE_RUN/$rel"
    else
      quarantine_move "$path" "$rel"
    fi
  else
    run "rm -f -- $(printf '%q' "$path")"
  fi
  count=$((count + 1))
done < "$MANIFEST"
log "clean-files: processed $count path(s). DRY_RUN=$DRY_RUN QUARANTINE=$QUARANTINE"

BASH;
	}

	/**
	 * @return string
	 */
	protected function script_clean_dirs() {
		return $this->bash_preamble() . <<<'BASH'
MANIFEST="$DIR/dirs.txt"
if [[ ! -f "$MANIFEST" ]]; then
  echo "Missing dirs.txt" >&2
  exit 1
fi
load_site_env
export QUARANTINE_RUN="${QUARANTINE_RUN:-$(date -u +%Y%m%d-%H%M%S)}"
count=0
while IFS= read -r path || [[ -n "$path" ]]; do
  [[ -z "$path" || "$path" == \#* ]] && continue
  if [[ ! -d "$path" ]]; then
    log "skip (missing dir): $path"
    continue
  fi
  if [[ "$QUARANTINE" == "1" ]]; then
    rel="$(rel_key_from_abspath "$path")"
    if [[ "$DRY_RUN" == "1" ]]; then
      log "[dry-run] quarantine tree $path -> $QUARANTINE_BASE/$QUARANTINE_RUN/$rel"
    else
      quarantine_move "$path" "$rel"
    fi
  else
    run "rm -rf -- $(printf '%q' "$path")"
  fi
  count=$((count + 1))
done < "$MANIFEST"
log "clean-dirs: processed $count path(s). DRY_RUN=$DRY_RUN QUARANTINE=$QUARANTINE"

BASH;
	}

	/**
	 * @return string
	 */
	protected function script_clean_options() {
		return $this->bash_preamble() . $this->bash_load_db_env() . <<<'BASH'
MANIFEST="$DIR/options.txt"
if [[ ! -f "$MANIFEST" ]]; then
  echo "Missing options.txt" >&2
  exit 1
fi
count=0
while IFS=$'\t' read -r table column value || [[ -n "${table:-}" ]]; do
  [[ -z "${table:-}" || "$table" == \#* ]] && continue
  if [[ "$column" != "option_name" ]]; then
    log "skip (unsupported column): $table $column $value"
    continue
  fi
  # Escape single quotes for SQL string literal.
  esc=${value//\'/\'\'}
  sql="DELETE FROM \`${table}\` WHERE option_name='${esc}' LIMIT 1;"
  if [[ "$DRY_RUN" == "1" ]]; then
    log "[dry-run] mysql: $sql"
  else
    log "+ DELETE option_name=$value"
    printf '%s\n' "$sql" | mysql_cmd
  fi
  count=$((count + 1))
done < "$MANIFEST"
log "clean-options: processed $count option(s). DRY_RUN=$DRY_RUN"

BASH;
	}

	/**
	 * @return string
	 */
	protected function script_clean_cron() {
		return $this->bash_preamble() . $this->bash_load_db_env() . <<<'BASH'
MANIFEST="$DIR/cron.txt"
if [[ ! -f "$MANIFEST" ]]; then
  echo "Missing cron.txt" >&2
  exit 1
fi

needles=()
while IFS=$'\t' read -r kind rest || [[ -n "${kind:-}" ]]; do
  [[ -z "${kind:-}" || "$kind" == \#* ]] && continue
  case "$kind" in
    WP_CRON_CLEAR)
      table="${TABLE_PREFIX}options"
      sql="UPDATE \`${table}\` SET option_value='' WHERE option_name='cron' LIMIT 1;"
      if [[ "$DRY_RUN" == "1" ]]; then
        log "[dry-run] mysql: $sql"
      else
        log "+ clear WP cron option"
        printf '%s\n' "$sql" | mysql_cmd
      fi
      ;;
    HOST_FILE)
      path="$rest"
      if [[ ! -e "$path" ]]; then
        log "skip (missing host cron file): $path"
        continue
      fi
      run "rm -f -- $(printf '%q' "$path")"
      ;;
    CRONTAB_NEEDLE)
      needles+=("$rest")
      ;;
    *)
      log "skip unknown cron directive: $kind"
      ;;
  esac
done < "$MANIFEST"

if ((${#needles[@]} > 0)); then
  if ! command -v crontab >/dev/null 2>&1; then
    log "crontab not available; skip user crontab strip"
  else
    tmp="$(mktemp)"
    if crontab -l >"$tmp" 2>/dev/null; then
      filtered="$(mktemp)"
      cp "$tmp" "$filtered"
      for n in "${needles[@]}"; do
        grep -v -F -- "$n" "$filtered" >"${filtered}.new" || true
        mv "${filtered}.new" "$filtered"
      done
      if [[ "$DRY_RUN" == "1" ]]; then
        log "[dry-run] would install filtered crontab (needles: ${needles[*]})"
        diff -u "$tmp" "$filtered" || true
      else
        log "+ install filtered crontab"
        crontab "$filtered"
      fi
      rm -f "$filtered"
    else
      log "no user crontab or cannot list; skip"
    fi
    rm -f "$tmp"
  fi
fi
log "clean-cron: done. DRY_RUN=$DRY_RUN"

BASH;
	}

	/**
	 * @return string
	 */
	protected function script_clean_users() {
		return $this->bash_preamble() . $this->bash_load_db_env() . <<<'BASH'
MANIFEST="$DIR/users.txt"
if [[ ! -f "$MANIFEST" ]]; then
  echo "Missing users.txt" >&2
  exit 1
fi
users_table="${TABLE_PREFIX}users"
meta_table="${TABLE_PREFIX}usermeta"
count=0
while IFS=$'\t' read -r id login || [[ -n "${id:-}" ]]; do
  [[ -z "${id:-}" || "$id" == \#* ]] && continue
  if ! [[ "$id" =~ ^[0-9]+$ ]]; then
    log "skip invalid user id: $id"
    continue
  fi
  sql_meta="DELETE FROM \`${meta_table}\` WHERE user_id=${id};"
  sql_user="DELETE FROM \`${users_table}\` WHERE ID=${id} LIMIT 1;"
  if [[ "$DRY_RUN" == "1" ]]; then
    log "[dry-run] delete user id=$id login=$login"
  else
    log "+ DELETE user id=$id login=$login"
    printf '%s\n' "$sql_meta" | mysql_cmd
    printf '%s\n' "$sql_user" | mysql_cmd
  fi
  count=$((count + 1))
done < "$MANIFEST"
log "clean-users: processed $count user(s). DRY_RUN=$DRY_RUN"

BASH;
	}

	/**
	 * @return string
	 */
	protected function script_clean_all() {
		return $this->bash_preamble() . <<<'BASH'
export QUARANTINE_RUN="${QUARANTINE_RUN:-$(date -u +%Y%m%d-%H%M%S)}"
log "== clean-all (DRY_RUN=$DRY_RUN QUARANTINE=$QUARANTINE RUN=$QUARANTINE_RUN) =="
"$DIR/clean-files.sh"
"$DIR/clean-dirs.sh"
"$DIR/clean-options.sh"
"$DIR/clean-cron.sh"
"$DIR/clean-users.sh"
log "== clean-all finished =="

BASH;
	}

	/**
	 * Short-lived live containment loop (outside WordPress).
	 *
	 * @return string
	 */
	protected function script_guard() {
		return $this->bash_preamble() . <<<'BASH'
# Temporary live containment. Does not prove the site is clean when found=0.
INTERVAL="${INTERVAL:-5}"
load_site_env
WATCH="$DIR/watch-paths.txt"
MARKERS_RE='SC_ADV_BEGIN|SC_DB_BEGIN|SC_TH_BEGIN|SC_WC|__SC_BOOT|SCOCV|echo-updater-x|retadpu-ohce|wp_helper_uid|Widget cache bootstrap, ver b2ccbcd25e|Runtime dependencies bootstrap 9b66554fd3|wp_179e4b|wp_4bb239|wp_4960ab|8e753f173a5c428fe6c44646cddb0da04952628bcd098400d6fe9fcd3f3bb435|b6efe58fb91fb0bb9d11fce3b6eb42bcc1b8822deacc39facc657d17cffb1bf5'

if [[ ! -f "$WATCH" ]]; then
  echo "Missing watch-paths.txt" >&2
  exit 1
fi

log "guard: INTERVAL=${INTERVAL}s QUARANTINE_BASE=$QUARANTINE_BASE"
log "guard: Ctrl+C to stop. found=0 is NOT proof of clean."

pass=0
while true; do
  pass=$((pass + 1))
  found=0
  moved=0
  export QUARANTINE_RUN="$(date -u +%Y%m%d-%H%M%S)"

  while IFS= read -r path || [[ -n "$path" ]]; do
    [[ -z "$path" || "$path" == \#* ]] && continue
    [[ -e "$path" || -L "$path" ]] || continue

    base="$(basename "$path")"
    hit=0
    note=""

    # Exact known high-value basenames always count when present on the watch list.
    case "$base" in
      object-cache.php|advanced-cache.php|db.php|.user.ini|user.ini)
        if grep -Eq "$MARKERS_RE|auto_prepend_file" -- "$path" 2>/dev/null; then
          hit=1
          note="dropin/prepend marker"
        elif [[ "$base" == ".user.ini" || "$base" == "user.ini" ]]; then
          if grep -Eq 'auto_prepend_file' -- "$path" 2>/dev/null; then
            hit=1
            note="auto_prepend_file"
          fi
        fi
        ;;
      admin-helper.php|boot-loader.php)
        file_sha="$(sha256sum -- "$path" 2>/dev/null | awk '{print $1}')"
        if [[ "$file_sha" == "4bbeaed0845bcd965c92902a1dfb314d4afd79e48029dc22bf5fa7597a0d93cb" \
           || "$file_sha" == "0cbe6a757abcfe7c8968ae169929164d978f120847c05ca91f5e09c44293c4f3" ]]; then
          hit=1
          note="wp_helper_uid exact file hash"
        elif grep -Eq 'wp_helper_uid|Widget cache bootstrap, ver b2ccbcd25e|Runtime dependencies bootstrap 9b66554fd3|8e753f173a5c428fe6c44646cddb0da04952628bcd098400d6fe9fcd3f3bb435|b6efe58fb91fb0bb9d11fce3b6eb42bcc1b8822deacc39facc657d17cffb1bf5' -- "$path" 2>/dev/null; then
          hit=1
          note="wp_helper_uid sample"
        elif grep -Eq 'wp_179e4b' -- "$path" 2>/dev/null \
          && grep -Eq 'wp_4bb239' -- "$path" 2>/dev/null \
          && grep -Eq 'wp_4960ab' -- "$path" 2>/dev/null; then
          hit=1
          note="wp_helper_uid cluster probes"
        fi
        ;;
      wp-config.php)
        if grep -Eq 'SC_WC|SC_WC_BEGIN|__SC_BOOT|SCOCV' -- "$path" 2>/dev/null; then
          hit=1
          note="wp-config marker"
        fi
        ;;
      *)
        # Returning purge targets, or hex-named staging drops.
        if [[ "$base" =~ ^[0-9a-f]{8}\.(php|zip)$ ]]; then
          hit=1
          note="hex staging name"
        elif grep -Eq "$MARKERS_RE" -- "$path" 2>/dev/null; then
          hit=1
          note="content marker"
        else
          # Path was on the export purge list — any reappearance is an IOC.
          hit=1
          note="watchlist reappear"
        fi
        ;;
    esac

    if [[ "$hit" -eq 1 ]]; then
      found=$((found + 1))
      log "[IOC] $path ($note)"
      rel="$(rel_key_from_abspath "$path")"
      if [[ "$DRY_RUN" == "1" ]]; then
        log "[dry-run] would quarantine $path"
      else
        if quarantine_move "$path" "$rel"; then
          moved=$((moved + 1))
        else
          log "[FAIL] quarantine $path"
        fi
      fi
    fi
  done < "$WATCH"

  # Also spot hex staging artifacts under wp-content (cheap find, depth-limited).
  if [[ -n "${WP_CONTENT_DIR:-}" && -d "$WP_CONTENT_DIR" ]]; then
    while IFS= read -r -d '' path; do
      found=$((found + 1))
      log "[IOC] $path (hex scan)"
      rel="$(rel_key_from_abspath "$path")"
      if [[ "$DRY_RUN" == "1" ]]; then
        log "[dry-run] would quarantine $path"
      else
        if quarantine_move "$path" "$rel"; then
          moved=$((moved + 1))
        fi
      fi
    done < <(find "$WP_CONTENT_DIR" -xdev \( -name '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f].php' -o -name '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f].zip' \) -type f -print0 2>/dev/null | head -z -n 50)
  fi

  log "[SUMMARY] pass=$pass found=$found moved=$moved"
  sleep "$INTERVAL"
done

BASH;
	}
}
